/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufg.inf.aed1.aed1.gui.jlabels;

import br.ufg.inf.aed1.aed1.projeto.AED1;
import br.ufg.inf.aed1.aed1.carta.*;
import br.ufg.inf.aed1.aed1.carta.filemanager.FileManager;
import br.ufg.inf.aed1.aed1.gameplay.Game;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.InvalidClassException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

class ComponentManager {

    public static void setAllCentralized(Container cont, Class classe) {
        for (Component comp : cont.getComponents()) {
            if (classe.isInstance(comp)) {
                try {
                    Method metodo = classe.getMethod("setHorizontalAlignment", new Class[]{int.class});
                    metodo.invoke(classe.cast(comp), SwingConstants.CENTER);
                } catch (NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                    Logger.getLogger(ComponentManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (comp instanceof Container) {
                setAllCentralized((Container) comp, classe);
            }
        }
    }
}

class myCellRenderer extends DefaultListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        setComponentOrientation(list.getComponentOrientation());
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        Carta object = (Carta) value;
        //String text = String.format("%-8.8s  %4.4s - %3d", object.getNome(),object.getSet(), object.getId());

        setText(object.getNome());
        return this;
    }
}

class myDeckCellRenderer extends DefaultListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        setComponentOrientation(list.getComponentOrientation());
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        Deck object = (Deck) value;
        //String text = String.format("%-8.8s  %4.4s - %3d", object.getNome(),object.getSet(), object.getId());

        setText(object.getNome());
        return this;
    }
}

public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();

        //n ta funcionando n sei pq, mas deveria
        //ComponentManager.setAllCentralized(this, JButton.class);
        NovoJogoJPanel.setVisible(false);
        EditarDeckJPanel.setVisible(false);
        NovoDeckJPanel.setVisible(false);
        NovaCartaJPanel.setVisible(false);
        JogoLocalSelecionaDeckJPanel.setVisible(false);

        ListaCartasJList.setCellRenderer(new myCellRenderer());
        ListaCartas2JList.setCellRenderer(new myCellRenderer());
        ListaDecks1JComboBox.setRenderer(new myDeckCellRenderer());
        ListaDecks2JComboBox.setRenderer(new myDeckCellRenderer());

        icone.setImage(icone.getImage().getScaledInstance(ImagemCartajLabel.getWidth(), ImagemCartajLabel.getHeight(), Image.SCALE_SMOOTH));

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        NovoJogoBtn = new javax.swing.JButton();
        EditarBaralhoBtn = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        NovoJogoJPanel = new javax.swing.JPanel();
        PartidaLocalBtn = new javax.swing.JButton();
        PartidaOnlineHostBtn = new javax.swing.JButton();
        PartidaOnlineGuestBtn = new javax.swing.JButton();
        Voltar_NovoJogoBtn = new javax.swing.JButton();
        EditarDeckJPanel = new javax.swing.JPanel();
        NovoDeckBtn = new javax.swing.JButton();
        NovaCartaBtn = new javax.swing.JButton();
        Voltar_EditarDeckBtn = new javax.swing.JButton();
        NovoDeckJPanel = new javax.swing.JPanel();
        ImagemCartajLabel = new javax.swing.JLabel();
        Voltar_NovoDeckBtn = new javax.swing.JButton();
        ListaCartasJScrollPane1 = new javax.swing.JScrollPane();
        ListaCartasJList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCartas2JList = new javax.swing.JList<>();
        RemoverCriaDeckBtn = new javax.swing.JButton();
        AdicionarCriaDeckBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QntCartasAdicionadasCriaDeckJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CriarDeckCriaDeckBtn = new javax.swing.JButton();
        NomeDeckTxtFiled = new javax.swing.JTextField();
        NovaCartaJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SetCartaTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idCartaTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeCartaTxtField = new javax.swing.JTextField();
        tiposMonstroJComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        VoltarNovaCartaBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipoAtributoJComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        EstrelasJComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ATKTxtField = new javax.swing.JTextField();
        DEFTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TipoMagiaJComboBox = new javax.swing.JComboBox<>();
        TipoCartaBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TipoCampoJComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        TipoTrapJComboBox = new javax.swing.JComboBox<>();
        ImagemCartajLabel1 = new javax.swing.JLabel();
        CriarCartaBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescricaoJTextArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        imgPathTxtField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JogoLocalSelecionaDeckJPanel = new javax.swing.JPanel();
        VoltarJogoLocalBtn = new javax.swing.JButton();
        ListaDecks1JComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ListaDecks2JComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        IniciarJogoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setName("Painel 1"); // NOI18N

        NovoJogoBtn.setText("Novo Jogo");
        NovoJogoBtn.setAlignmentX(0.5F);
        NovoJogoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NovoJogoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NovoJogoBtn.setName("Novo Jogo"); // NOI18N
        NovoJogoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoJogoBtnMouseClicked(evt);
            }
        });
        NovoJogoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoJogoBtnActionPerformed(evt);
            }
        });

        EditarBaralhoBtn.setText("Editar Baralho");
        EditarBaralhoBtn.setAlignmentX(0.5F);
        EditarBaralhoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarBaralhoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarBaralhoBtn.setName("Editar Baralho"); // NOI18N
        EditarBaralhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBaralhoBtnActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.setAlignmentX(0.5F);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sair.setName(""); // NOI18N
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(NovoJogoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarBaralhoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(NovoJogoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarBaralhoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(Sair)
                .addGap(61, 61, 61))
        );

        NovoJogoJPanel.setBackground(new java.awt.Color(153, 153, 153));
        NovoJogoJPanel.setName("NovoJogo JPanel"); // NOI18N
        NovoJogoJPanel.setPreferredSize(new java.awt.Dimension(537, 474));

        PartidaLocalBtn.setText("Partida Local");
        PartidaLocalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PartidaLocalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidaLocalBtnActionPerformed(evt);
            }
        });

        PartidaOnlineHostBtn.setText("Criar Partida");
        PartidaOnlineHostBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PartidaOnlineHostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidaOnlineHostBtnActionPerformed(evt);
            }
        });

        PartidaOnlineGuestBtn.setText("Conectar-se a Partida");
        PartidaOnlineGuestBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PartidaOnlineGuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidaOnlineGuestBtnActionPerformed(evt);
            }
        });

        Voltar_NovoJogoBtn.setText("Voltar");
        Voltar_NovoJogoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar_NovoJogoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar_NovoJogoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NovoJogoJPanelLayout = new javax.swing.GroupLayout(NovoJogoJPanel);
        NovoJogoJPanel.setLayout(NovoJogoJPanelLayout);
        NovoJogoJPanelLayout.setHorizontalGroup(
            NovoJogoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovoJogoJPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(NovoJogoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PartidaOnlineHostBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PartidaLocalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Voltar_NovoJogoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PartidaOnlineGuestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(175, 175, 175))
        );
        NovoJogoJPanelLayout.setVerticalGroup(
            NovoJogoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovoJogoJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(PartidaLocalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(PartidaOnlineHostBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PartidaOnlineGuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(Voltar_NovoJogoBtn)
                .addGap(61, 61, 61))
        );

        EditarDeckJPanel.setBackground(new java.awt.Color(153, 153, 153));
        EditarDeckJPanel.setName("Painel 3"); // NOI18N
        EditarDeckJPanel.setPreferredSize(new java.awt.Dimension(537, 474));

        NovoDeckBtn.setText("Novo Deck");
        NovoDeckBtn.setName("NovoDeck"); // NOI18N
        NovoDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoDeckBtnActionPerformed(evt);
            }
        });

        NovaCartaBtn.setText("Nova Carta");
        NovaCartaBtn.setName("NovaCarta"); // NOI18N
        NovaCartaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaCartaBtnActionPerformed(evt);
            }
        });

        Voltar_EditarDeckBtn.setText("Voltar");
        Voltar_EditarDeckBtn.setName("VoltarEditarDeck"); // NOI18N
        Voltar_EditarDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar_EditarDeckBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditarDeckJPanelLayout = new javax.swing.GroupLayout(EditarDeckJPanel);
        EditarDeckJPanel.setLayout(EditarDeckJPanelLayout);
        EditarDeckJPanelLayout.setHorizontalGroup(
            EditarDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarDeckJPanelLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(EditarDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Voltar_EditarDeckBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NovaCartaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NovoDeckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        EditarDeckJPanelLayout.setVerticalGroup(
            EditarDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarDeckJPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(NovoDeckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(NovaCartaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(Voltar_EditarDeckBtn)
                .addGap(61, 61, 61))
        );

        Voltar_EditarDeckBtn.getAccessibleContext().setAccessibleName("Voltar editarDeck");

        NovoDeckJPanel.setBackground(new java.awt.Color(153, 153, 153));
        NovoDeckJPanel.setName("NovoDeckJPanel"); // NOI18N
        NovoDeckJPanel.setPreferredSize(new java.awt.Dimension(537, 474));

        //ImagemCartajLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Pics/cartaParaBaixo.png"))); // NOI18N
        //ImagemCartajLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("../pics/cartaParaBaixo.png"))); // NOI18N
        ImagemCartajLabel.setIcon(createImageIcon("/pics/cartaParaBaixo.png", "Imagem do icone")); // NOI18N
        

        Voltar_NovoDeckBtn.setText("Cancelar");
        Voltar_NovoDeckBtn.setName("Voltar_NovoDeckBtn"); // NOI18N
        Voltar_NovoDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar_NovoDeckBtnActionPerformed(evt);
            }
        });

        Carta[] listaTodasCartasCriaDeck = new Carta[AED1.todasAsCartas.length];
        System.arraycopy( AED1.todasAsCartas.getCartasArray(), 0, listaTodasCartasCriaDeck, 0, listaTodasCartasCriaDeck.length );
        ListaCartasJList.setModel( new javax.swing.DefaultListModel<Carta>() );
        ListaCartasJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaCartasJListMouseClicked(evt);
            }
        });
        for(Carta elemento: listaTodasCartasCriaDeck){
            ((DefaultListModel)ListaCartasJList.getModel()).addElement(elemento);
        }
        ListaCartasJScrollPane1.setViewportView(ListaCartasJList);

        ListaCartas2JList.setModel(new javax.swing.DefaultListModel<Carta>());
        ListaCartas2JList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaCartas2JListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaCartas2JList);

        RemoverCriaDeckBtn.setText("Remover");
        RemoverCriaDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverCriaDeckBtnActionPerformed(evt);
            }
        });

        AdicionarCriaDeckBtn.setText("Adicionar");
        AdicionarCriaDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarCriaDeckBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cartas Disponiveis");

        jLabel2.setText("Cartas Selecionadas");

        QntCartasAdicionadasCriaDeckJLabel.setText("0");

        jLabel4.setText("/40");

        CriarDeckCriaDeckBtn.setText("Concluir");
        CriarDeckCriaDeckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarDeckCriaDeckBtnActionPerformed(evt);
            }
        });

        NomeDeckTxtFiled.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NomeDeckTxtFiled.setText("Nome");

        javax.swing.GroupLayout NovoDeckJPanelLayout = new javax.swing.GroupLayout(NovoDeckJPanel);
        NovoDeckJPanel.setLayout(NovoDeckJPanelLayout);
        NovoDeckJPanelLayout.setHorizontalGroup(
            NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QntCartasAdicionadasCriaDeckJLabel)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovoDeckJPanelLayout.createSequentialGroup()
                        .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(NomeDeckTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(CriarDeckCriaDeckBtn))
                            .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                                .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                                        .addComponent(RemoverCriaDeckBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AdicionarCriaDeckBtn))
                                    .addComponent(ListaCartasJScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImagemCartajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Voltar_NovoDeckBtn)
                .addGap(450, 450, 450))
        );
        NovoDeckJPanelLayout.setVerticalGroup(
            NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovoDeckJPanelLayout.createSequentialGroup()
                .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ImagemCartajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NovoDeckJPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaCartasJScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoverCriaDeckBtn)
                            .addComponent(AdicionarCriaDeckBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(QntCartasAdicionadasCriaDeckJLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(NovoDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar_NovoDeckBtn)
                    .addComponent(CriarDeckCriaDeckBtn)
                    .addComponent(NomeDeckTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Voltar_NovoDeckBtn.getAccessibleContext().setAccessibleName("Voltar_NovoDeckBtn");

        NovaCartaJPanel.setBackground(new java.awt.Color(153, 153, 153));
        NovaCartaJPanel.setPreferredSize(new java.awt.Dimension(537, 474));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SET-ID");

        SetCartaTxtField.setText("Set");
        SetCartaTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SetCartaTxtFieldKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("-");

        idCartaTxtField.setText("0");
        idCartaTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idCartaTxtFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nome");

        nomeCartaTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeCartaTxtFieldKeyReleased(evt);
            }
        });

        tiposMonstroJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(CartaMonstro.TipoMonstro.values() ));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tipo Carta");

        VoltarNovaCartaBtn.setText("Cancelar");
        VoltarNovaCartaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarNovaCartaBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tipo Monstro");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Atributo");

        tipoAtributoJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(CartaMonstro.TipoAtributo.values() ));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Estrelas");

        EstrelasJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 11, 12, 0 }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ATK / DEF");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(" / ");

        ATKTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ATKTxtFieldKeyReleased(evt);
            }
        });

        DEFTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DEFTxtFieldKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tipo Magia");

        TipoMagiaJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>( CartaMagica.TipoEfeitoMagico.values() ));
        TipoMagiaJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoMagiaJComboBoxItemStateChanged(evt);
            }
        });
        TipoMagiaJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMagiaJComboBoxActionPerformed(evt);
            }
        });

        TipoCartaBtn.setText("Carta Monstro");
        TipoCartaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCartaBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tipo Campo");

        TipoCampoJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>( Game.TipoCampo.values() ));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tipo Trap");

        TipoTrapJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>( Game.TipoTrap.values() ));

        //ImagemCartajLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Pics/cartaParaBaixo.png"))); // NOI18N
		ImagemCartajLabel1.setIcon(createImageIcon("/pics/cartaParaBaixo.png", "Imagem do icone")); // NOI18N
		
        CriarCartaBtn.setText("Criar");
        CriarCartaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarCartaBtnActionPerformed(evt);
            }
        });

        DescricaoJTextArea.setColumns(20);
        DescricaoJTextArea.setRows(5);
        DescricaoJTextArea.setText("...");
        jScrollPane2.setViewportView(DescricaoJTextArea);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Descrição");

        imgPathTxtField.setText("Path / URL");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Img");

        //jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Pics/PastaIconMini.png"))); // NOI18N
        jButton1.setIcon(createImageIcon("/pics/PastaIconMini.png", "Imagem do icone")); // NOI18N
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NovaCartaJPanelLayout = new javax.swing.GroupLayout(NovaCartaJPanel);
        NovaCartaJPanel.setLayout(NovaCartaJPanelLayout);
        NovaCartaJPanelLayout.setHorizontalGroup(
            NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                .addComponent(VoltarNovaCartaBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(idCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TipoCartaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovaCartaJPanelLayout.createSequentialGroup()
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                                .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EstrelasJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TipoMagiaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TipoCampoJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NovaCartaJPanelLayout.createSequentialGroup()
                                                    .addComponent(ATKTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(DEFTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tipoAtributoJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tiposMonstroJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TipoTrapJComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(62, 62, 62)
                                        .addComponent(nomeCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovaCartaJPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(6, 6, 6)))
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                                .addComponent(imgPathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CriarCartaBtn))
                            .addComponent(ImagemCartajLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        NovaCartaJPanelLayout.setVerticalGroup(
            NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(SetCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(idCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(TipoCartaBtn)))
                .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomeCartaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tiposMonstroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tipoAtributoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EstrelasJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ATKTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DEFTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TipoMagiaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TipoCampoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TipoTrapJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addComponent(ImagemCartajLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(VoltarNovaCartaBtn)
                        .addContainerGap())
                    .addGroup(NovaCartaJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NovaCartaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CriarCartaBtn)
                            .addComponent(imgPathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        JogoLocalSelecionaDeckJPanel.setBackground(new java.awt.Color(153, 153, 153));
        JogoLocalSelecionaDeckJPanel.setName("Painel 1"); // NOI18N

        VoltarJogoLocalBtn.setText("Voltar");
        VoltarJogoLocalBtn.setAlignmentX(0.5F);
        VoltarJogoLocalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarJogoLocalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VoltarJogoLocalBtn.setName(""); // NOI18N
        VoltarJogoLocalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarJogoLocalBtnActionPerformed(evt);
            }
        });

        Deck todosDecksArray[] = new Deck[ AED1.todosOsDecks.size()];
        todosDecksArray = AED1.todosOsDecks.toArray(todosDecksArray);
        ListaDecks1JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>( todosDecksArray ));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Jogador 1");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Escolham seu Deck");

        //Deck todosDecksArray[] = new Deck[ AED1.todosOsDecks.size()];
        //todosDecksArray = ATAED1.todosOsDecks.toArray(todosDecksArray);
        ListaDecks2JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(todosDecksArray));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Jogador 2");

        IniciarJogoBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IniciarJogoBtn.setText("Iniciar");
        IniciarJogoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJogoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JogoLocalSelecionaDeckJPanelLayout = new javax.swing.GroupLayout(JogoLocalSelecionaDeckJPanel);
        JogoLocalSelecionaDeckJPanel.setLayout(JogoLocalSelecionaDeckJPanelLayout);
        JogoLocalSelecionaDeckJPanelLayout.setHorizontalGroup(
            JogoLocalSelecionaDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                .addGap(0, 178, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(169, 169, 169))
            .addGroup(JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(JogoLocalSelecionaDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListaDecks1JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JogoLocalSelecionaDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListaDecks2JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(77, 77, 77))
            .addGroup(JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(VoltarJogoLocalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IniciarJogoBtn)
                .addGap(222, 222, 222))
        );
        JogoLocalSelecionaDeckJPanelLayout.setVerticalGroup(
            JogoLocalSelecionaDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(JogoLocalSelecionaDeckJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(ListaDecks1JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JogoLocalSelecionaDeckJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(ListaDecks2JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(IniciarJogoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(VoltarJogoLocalBtn)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NovoJogoJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EditarDeckJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NovoDeckJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NovaCartaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(JogoLocalSelecionaDeckJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NovoJogoJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EditarDeckJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NovoDeckJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NovaCartaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(JogoLocalSelecionaDeckJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        NovoJogoJPanel.getAccessibleContext().setAccessibleName("");
        NovoDeckJPanel.getAccessibleContext().setAccessibleName("NovoDeckJPanel");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoJogoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoJogoBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        NovoJogoJPanel.setVisible(true);
    }//GEN-LAST:event_NovoJogoBtnActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_SairActionPerformed

    private void EditarBaralhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBaralhoBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        EditarDeckJPanel.setVisible(true);
    }//GEN-LAST:event_EditarBaralhoBtnActionPerformed

    private void PartidaOnlineHostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidaOnlineHostBtnActionPerformed
        try {
            AED1.jogaOnlineHost();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PartidaOnlineHostBtnActionPerformed

    private void NovoJogoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoJogoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NovoJogoBtnMouseClicked

    private void PartidaLocalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidaLocalBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        JogoLocalSelecionaDeckJPanel.setVisible(true);
    }//GEN-LAST:event_PartidaLocalBtnActionPerformed

    private void Voltar_NovoJogoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar_NovoJogoBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_Voltar_NovoJogoBtnActionPerformed

    private void PartidaOnlineGuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidaOnlineGuestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidaOnlineGuestBtnActionPerformed

    private void NovaCartaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaCartaBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        NovaCartaJPanel.setVisible(true);
        ImagemCartajLabel1.setIcon(icone);

        CriarCartaBtn.setEnabled(false);

        tipoCartaTxt = "Carta Monstro";
        TipoMagiaJComboBox.setEnabled(false);
        TipoTrapJComboBox.setEnabled(false);
        TipoCampoJComboBox.setEnabled(false);

        tiposMonstroJComboBox.setEnabled(true);
        tipoAtributoJComboBox.setEnabled(true);
        EstrelasJComboBox.setEnabled(true);
        ATKTxtField.setEnabled(true);
        DEFTxtField.setEnabled(true);
    }//GEN-LAST:event_NovaCartaBtnActionPerformed

    private void Voltar_EditarDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar_EditarDeckBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_Voltar_EditarDeckBtnActionPerformed

    private void NovoDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoDeckBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        ImagemCartajLabel.setIcon(icone);
        qntCartasAdicionadas = 0;
        QntCartasAdicionadasCriaDeckJLabel.setText("0");
        CriarDeckCriaDeckBtn.setEnabled(false);
        NovoDeckJPanel.setVisible(true);
    }//GEN-LAST:event_NovoDeckBtnActionPerformed

    private void ListaCartasJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCartasJListMouseClicked
        Carta cartaSelecionada = ListaCartasJList.getSelectedValue();
        ImageIcon icone = new ImageIcon(cartaSelecionada.getImageSrc());
        icone.setImage(icone.getImage().getScaledInstance(ImagemCartajLabel.getWidth(), ImagemCartajLabel.getHeight(), Image.SCALE_SMOOTH));
        ImagemCartajLabel.setIcon(icone);
    }//GEN-LAST:event_ListaCartasJListMouseClicked

    private void Voltar_NovoDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar_NovoDeckBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        EditarDeckJPanel.setVisible(true);
    }//GEN-LAST:event_Voltar_NovoDeckBtnActionPerformed

    private void AdicionarCriaDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarCriaDeckBtnActionPerformed
        Carta cartaSelecionada = ListaCartasJList.getSelectedValue();
        if (ListaCartas2JList.getModel() instanceof DefaultListModel && qntCartasAdicionadas < Deck.DECK_SIZE) {
            DefaultListModel modelo = (DefaultListModel) ListaCartas2JList.getModel();
            modelo.addElement(cartaSelecionada);
            qntCartasAdicionadas++;
            QntCartasAdicionadasCriaDeckJLabel.setText(qntCartasAdicionadas + "");
        }
        if (qntCartasAdicionadas == Deck.DECK_SIZE) {
            CriarDeckCriaDeckBtn.setEnabled(true);
        }

    }//GEN-LAST:event_AdicionarCriaDeckBtnActionPerformed

    private void RemoverCriaDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverCriaDeckBtnActionPerformed
        Carta cartaSelecionada = ListaCartas2JList.getSelectedValue();
        if (ListaCartas2JList.getModel() instanceof DefaultListModel) {
            DefaultListModel modelo = (DefaultListModel) ListaCartas2JList.getModel();
            if (modelo.removeElement(cartaSelecionada)) {
                qntCartasAdicionadas--;
                QntCartasAdicionadasCriaDeckJLabel.setText(qntCartasAdicionadas + "");
            }
        }
    }//GEN-LAST:event_RemoverCriaDeckBtnActionPerformed

    private void ListaCartas2JListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCartas2JListMouseClicked
        Carta cartaSelecionada = ListaCartas2JList.getSelectedValue();
        ImageIcon icone = new ImageIcon(cartaSelecionada.getImageSrc());
        icone.setImage(icone.getImage().getScaledInstance(ImagemCartajLabel.getWidth(), ImagemCartajLabel.getHeight(), Image.SCALE_SMOOTH));
        ImagemCartajLabel.setIcon(icone);
    }//GEN-LAST:event_ListaCartas2JListMouseClicked

    private void CriarDeckCriaDeckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarDeckCriaDeckBtnActionPerformed
        CriarDeckCriaDeckBtn.setEnabled(false);
        String nome = NomeDeckTxtFiled.getText();
        Deck deck = new Deck(nome);
        for (int i = 0; i < Deck.DECK_SIZE; i++) {
            Carta carta;
            carta = ListaCartas2JList.getModel().getElementAt(i);
            deck.addCarta(carta);
        }

        FileManager.writeDeck(deck);
        AED1.todosOsDecks.add(deck);
        ((DefaultComboBoxModel) ListaDecks1JComboBox.getModel()).addElement(deck);
        ((DefaultComboBoxModel) ListaDecks2JComboBox.getModel()).addElement(deck);
        JOptionPane.showMessageDialog(null, "Deck " + nome + " Criado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CriarDeckCriaDeckBtnActionPerformed

    private void VoltarNovaCartaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarNovaCartaBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        EditarDeckJPanel.setVisible(true);
    }//GEN-LAST:event_VoltarNovaCartaBtnActionPerformed

    private void TipoCartaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCartaBtnActionPerformed

        if (TipoCartaBtn.getText().equals("Carta Monstro")) {
            tipoCartaTxt = "Carta Magica";
            TipoMagiaJComboBox.setEnabled(true);
            //TipoTrapJComboBox.setEnabled(true);
            //TipoCampoJComboBox.setEnabled(true);

            tiposMonstroJComboBox.setEnabled(false);
            tipoAtributoJComboBox.setEnabled(false);
            EstrelasJComboBox.setEnabled(false);
            ATKTxtField.setEnabled(false);
            DEFTxtField.setEnabled(false);
        }
        if (TipoCartaBtn.getText().equals("Carta Magica")) {
            tipoCartaTxt = "Carta Monstro";

            TipoMagiaJComboBox.setEnabled(false);
            TipoTrapJComboBox.setEnabled(false);
            TipoCampoJComboBox.setEnabled(false);

            tiposMonstroJComboBox.setEnabled(true);
            tipoAtributoJComboBox.setEnabled(true);
            EstrelasJComboBox.setEnabled(true);
            ATKTxtField.setEnabled(true);
            DEFTxtField.setEnabled(true);
        }
        TipoCartaBtn.setText(tipoCartaTxt);
    }//GEN-LAST:event_TipoCartaBtnActionPerformed

    private void SetCartaTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SetCartaTxtFieldKeyReleased
        if (podeCriarCarta())
            CriarCartaBtn.setEnabled(true);
    }//GEN-LAST:event_SetCartaTxtFieldKeyReleased

    private void idCartaTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCartaTxtFieldKeyReleased
        if (podeCriarCarta())
            CriarCartaBtn.setEnabled(true);
    }//GEN-LAST:event_idCartaTxtFieldKeyReleased

    private void nomeCartaTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCartaTxtFieldKeyReleased
        if (podeCriarCarta())
            CriarCartaBtn.setEnabled(true);
    }//GEN-LAST:event_nomeCartaTxtFieldKeyReleased

    private void ATKTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATKTxtFieldKeyReleased
        if (podeCriarCarta())
            CriarCartaBtn.setEnabled(true);
    }//GEN-LAST:event_ATKTxtFieldKeyReleased

    private void DEFTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DEFTxtFieldKeyReleased
        if (podeCriarCarta())
            CriarCartaBtn.setEnabled(true);
    }//GEN-LAST:event_DEFTxtFieldKeyReleased

    private void CriarCartaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarCartaBtnActionPerformed
        if (tipoCartaTxt.equals("Carta Monstro")) {
            int atk = Integer.parseInt(ATKTxtField.getText());
            int def = Integer.parseInt(DEFTxtField.getText());
            int id = Integer.parseInt(idCartaTxtField.getText());
            String tipoMonstro = ((CartaMonstro.TipoMonstro) tiposMonstroJComboBox.getSelectedItem()).name();
            String atributo = ((CartaMonstro.TipoAtributo) tipoAtributoJComboBox.getSelectedItem()).name();

            CartaMonstro novaCarta = new CartaMonstro(nomeCartaTxtField.getText(), atk, def, tipoMonstro, atributo, SetCartaTxtField.getText(), id, imgPathTxtField.getText(), DescricaoJTextArea.getText());

            ImageIcon icone = new ImageIcon(novaCarta.getImageSrc());
            icone.setImage(icone.getImage().getScaledInstance(ImagemCartajLabel1.getWidth(), ImagemCartajLabel1.getHeight(), Image.SCALE_SMOOTH));
            ImagemCartajLabel1.setIcon(icone);

            ((DefaultListModel) ListaCartasJList.getModel()).addElement(novaCarta);
            AED1.todasAsCartas.addCarta(novaCarta);
            FileManager.writeCarta(novaCarta);
            JOptionPane.showMessageDialog(null, "Carta " + nomeCartaTxtField.getText() + " Criada com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);

        }
        if (tipoCartaTxt.equals("Carta Magica")) {

            int id = Integer.parseInt(idCartaTxtField.getText());
            CartaMagica.TipoEfeitoMagico tipoMagia = ((CartaMagica.TipoEfeitoMagico) TipoMagiaJComboBox.getSelectedItem());
            CartaMagica novaCarta = null;

            if (tipoMagia == CartaMagica.TipoEfeitoMagico.CAMPO) {
                novaCarta = new CartaMagica(nomeCartaTxtField.getText(), SetCartaTxtField.getText(), id, (Game.TipoCampo) TipoCampoJComboBox.getSelectedItem(), imgPathTxtField.getText(), DescricaoJTextArea.getText());
            }
            if (tipoMagia == CartaMagica.TipoEfeitoMagico.TRAP) {
                novaCarta = new CartaMagica(nomeCartaTxtField.getText(), SetCartaTxtField.getText(), id, (Game.TipoTrap) TipoTrapJComboBox.getSelectedItem(), imgPathTxtField.getText(), DescricaoJTextArea.getText());
            }

            ImageIcon icone = new ImageIcon(novaCarta.getImageSrc());
            icone.setImage(icone.getImage().getScaledInstance(ImagemCartajLabel1.getWidth(), ImagemCartajLabel1.getHeight(), Image.SCALE_SMOOTH));
            ImagemCartajLabel1.setIcon(icone);

            ((DefaultListModel) ListaCartasJList.getModel()).addElement(novaCarta);
            AED1.todasAsCartas.addCarta(novaCarta);
            FileManager.writeCarta(novaCarta);
            JOptionPane.showMessageDialog(null, "Carta " + nomeCartaTxtField.getText() + " Criada com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_CriarCartaBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (seletorDeArquivo.showOpenDialog(NovaCartaJPanel) == JFileChooser.APPROVE_OPTION) {
            String path = seletorDeArquivo.getSelectedFile().getAbsolutePath();
            imgPathTxtField.setText(path);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VoltarJogoLocalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarJogoLocalBtnActionPerformed
        ((JButton) evt.getSource()).getParent().setVisible(false);
        NovoJogoJPanel.setVisible(true);
    }//GEN-LAST:event_VoltarJogoLocalBtnActionPerformed

    private void IniciarJogoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJogoBtnActionPerformed
        DeckJogavel deckP1 = new DeckJogavel(AED1.todosOsDecks.get(0));
        DeckJogavel deckP2 = new DeckJogavel((Deck) ListaDecks2JComboBox.getSelectedItem());

        AED1.game.inicializa(deckP1, deckP2);
        /*
        System.out.println(deckP1.getNome());
        System.out.println(deckP2.getNome());
        for(Carta carta: deckP1.cartas){
            System.out.println(carta);
        }*/

        InGameInterface interfaceJogo = new InGameInterface(AED1.game);
        interfaceJogo.start();

        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_IniciarJogoBtnActionPerformed

    private void TipoMagiaJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoMagiaJComboBoxItemStateChanged
        JComboBox comboBox = (JComboBox) evt.getSource();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (((CartaMagica.TipoEfeitoMagico) comboBox.getSelectedItem()) == CartaMagica.TipoEfeitoMagico.CAMPO) {
                TipoCampoJComboBox.setEnabled(true);
                TipoTrapJComboBox.setEnabled(false);
            }
            if (((CartaMagica.TipoEfeitoMagico) comboBox.getSelectedItem()) == CartaMagica.TipoEfeitoMagico.TRAP) {
                TipoTrapJComboBox.setEnabled(true);
                TipoCampoJComboBox.setEnabled(false);
            }
        }
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            TipoTrapJComboBox.setEnabled(false);
            TipoCampoJComboBox.setEnabled(false);
        }

        if (podeCriarCarta()) {
            CriarCartaBtn.setEnabled(true);
        }


    }//GEN-LAST:event_TipoMagiaJComboBoxItemStateChanged

    private void TipoMagiaJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMagiaJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoMagiaJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    public boolean podeCriarCarta() {

        System.out.println("verificando se pode criar carta");
        if (SetCartaTxtField.getText().equals("")) {
            System.out.println("set");
            return false;
        }
        if (idCartaTxtField.getText().equals("")) {
            try {
                Integer.parseInt(idCartaTxtField.getText());
            } catch (NumberFormatException ex) {
                return false;
            }
        }
        if (nomeCartaTxtField.getText().equals("")) {
            System.out.println("Nome");
            return false;
        }

        if (tipoCartaTxt.equals("Carta Monstro")) {
            try {
                Integer.parseInt(ATKTxtField.getText());
            } catch (NumberFormatException ex) {
                return false;
            }

            try {
                Integer.parseInt(DEFTxtField.getText());
            } catch (NumberFormatException ex) {
                return false;
            }
        }
        return true;
    }

    String tipoCartaTxt = "Carta Monstro";
    ImageIcon icone = createImageIcon("/pics/cartaParaBaixo.png", "Imagem do icone");
    int qntCartasAdicionadas;
    
    /** Returns an ImageIcon, or null if the path was invalid. */
    private ImageIcon createImageIcon(String path, String description) {
        java.net.URL imgUrl = getClass().getResource(path);
        
        if (imgUrl != null) {
            return new ImageIcon(imgUrl, description);
        } else {
            return null;
        }
    }
    
    private JFileChooser seletorDeArquivo = new JFileChooser();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATKTxtField;
    private javax.swing.JButton AdicionarCriaDeckBtn;
    private javax.swing.JButton CriarCartaBtn;
    private javax.swing.JButton CriarDeckCriaDeckBtn;
    private javax.swing.JTextField DEFTxtField;
    private javax.swing.JTextArea DescricaoJTextArea;
    private javax.swing.JButton EditarBaralhoBtn;
    private javax.swing.JPanel EditarDeckJPanel;
    private javax.swing.JComboBox<Integer> EstrelasJComboBox;
    private javax.swing.JLabel ImagemCartajLabel;
    private javax.swing.JLabel ImagemCartajLabel1;
    private javax.swing.JButton IniciarJogoBtn;
    private javax.swing.JPanel JogoLocalSelecionaDeckJPanel;
    private javax.swing.JList<Carta> ListaCartas2JList;
    private javax.swing.JList<Carta> ListaCartasJList;
    private javax.swing.JScrollPane ListaCartasJScrollPane1;
    private javax.swing.JComboBox<Deck> ListaDecks1JComboBox;
    private javax.swing.JComboBox<Deck> ListaDecks2JComboBox;
    private javax.swing.JTextField NomeDeckTxtFiled;
    private javax.swing.JButton NovaCartaBtn;
    private javax.swing.JPanel NovaCartaJPanel;
    private javax.swing.JButton NovoDeckBtn;
    private javax.swing.JPanel NovoDeckJPanel;
    private javax.swing.JButton NovoJogoBtn;
    private javax.swing.JPanel NovoJogoJPanel;
    private javax.swing.JButton PartidaLocalBtn;
    private javax.swing.JButton PartidaOnlineGuestBtn;
    private javax.swing.JButton PartidaOnlineHostBtn;
    private javax.swing.JLabel QntCartasAdicionadasCriaDeckJLabel;
    private javax.swing.JButton RemoverCriaDeckBtn;
    private javax.swing.JButton Sair;
    private javax.swing.JTextField SetCartaTxtField;
    private javax.swing.JComboBox<Game.TipoCampo> TipoCampoJComboBox;
    private javax.swing.JButton TipoCartaBtn;
    private javax.swing.JComboBox<CartaMagica.TipoEfeitoMagico> TipoMagiaJComboBox;
    private javax.swing.JComboBox<Game.TipoTrap> TipoTrapJComboBox;
    private javax.swing.JButton VoltarJogoLocalBtn;
    private javax.swing.JButton VoltarNovaCartaBtn;
    private javax.swing.JButton Voltar_EditarDeckBtn;
    private javax.swing.JButton Voltar_NovoDeckBtn;
    private javax.swing.JButton Voltar_NovoJogoBtn;
    private javax.swing.JTextField idCartaTxtField;
    private javax.swing.JTextField imgPathTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeCartaTxtField;
    private javax.swing.JComboBox<CartaMonstro.TipoAtributo> tipoAtributoJComboBox;
    private javax.swing.JComboBox<CartaMonstro.TipoMonstro> tiposMonstroJComboBox;
    // End of variables declaration//GEN-END:variables
}
